### ISSUE TITLE
Error while starting...

### ISSUE THREAD

**Issue by bobhenl** [ComplexCodegit/HidePlugins-Project#3]
```
[20:35:55] [Server thread/INFO]: [HidePlugins_Project] Enabling HidePlugins_Project v2.8.1
[20:35:55] [Server thread/ERROR]: Error occurred while enabling HidePlugins_Project v2.8.1 (Is it up to date?)
java.lang.NullPointerException: null
    at io.github.complexcodegit.hidepluginsproject.utils.Utils.toList(Utils.java:113) ~[?:?]
    at io.github.complexcodegit.hidepluginsproject.managers.GroupManager.generateGroups(GroupManager.java:46) ~[?:?]
    at io.github.complexcodegit.hidepluginsproject.HidePluginsProject.onEnable(HidePluginsProject.java:34) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-345]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-345]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-345]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-345]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-345]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-345]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-345]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:907) ~[patched_1.15.2.jar:git-Paper-345]
    at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by bobhenl** [comment]
Was probably caused by missing [], but you could look on it.

**Comment by br14n-sol** [comment]
Hello! I regret not having responded.
I have not been developing this project for a long time, so I recommend moving to one with better support.
